name: RankUp
main: rankup\RankUp
version: 0.4.0
author: Falkirks
api: [3.0.0]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney", "PurePerms"]
permissions:
 rankup:
  default: true
  children:
    rankup.rankup:
      default: true
      description:
    rankup.admin:
      default: op
      description:
    rankup.groups:
      default: false
      description:
